FROM python:3.10-slim

WORKDIR /app

COPY docker/joytag-infer/requirements.cpu.txt /tmp/requirements.cpu.txt
COPY docker/joytag-infer/requirements.base.txt /tmp/requirements.base.txt
RUN pip install --no-cache-dir -r /tmp/requirements.cpu.txt

COPY docker/joytag-infer/app /app

ENV PYTHONPATH=/app
EXPOSE 8001

CMD ["python", "-m", "joytag_infer"]
