BATCH_STATE_PENDING = "pending"
BATCH_STATE_RUNNING = "running"
BATCH_STATE_COMPLETED = "completed"
BATCH_STATE_FAILED = "failed"

ITEM_STATE_PENDING = "pending"
ITEM_STATE_RUNNING = "running"
ITEM_STATE_REMOTE_UPLOADED = "remote_uploaded"
ITEM_STATE_SUCCEEDED = "succeeded"
ITEM_STATE_FAILED = "failed"
ITEM_STATE_CLEANUP_FAILED = "cleanup_failed"
# 被新批次接管的老 item，不再参与状态视图与重试保护。
ITEM_STATE_RETRIED = "retried"

ITEM_ACTION_RAPID_UPLOAD = "rapid_upload"
ITEM_ACTION_CLEANUP_ONLY = "cleanup_only"
ITEM_ACTION_RESUME_REMOTE = "resume_remote"
RETRYABLE_ITEM_STATES = {ITEM_STATE_FAILED, ITEM_STATE_CLEANUP_FAILED}

FAILURE_REASON_NOT_HIT = "not_hit"
FAILURE_REASON_FILE_CHANGED = "file_changed"
FAILURE_REASON_REMOTE_ERROR = "remote_error"
FAILURE_REASON_VERIFICATION_FAILED = "verification_failed"
FAILURE_REASON_OTHER = "other"
FAILURE_REASON_RISK_CONTROL = "risk_control"

TASK_KEY = "media_rapid_upload"
GENERIC_ITEM_ERROR = "秒传失败"
GENERIC_CLEANUP_ERROR = "本地文件删除失败"
GENERIC_RISK_CONTROL_ERROR = (
    "触发 115 风控（HTTP 405），已中止本批以避免加深封禁，请稍后重试"
)

PUBLIC_STATUS_NOT_HIT = "not_hit"
PUBLIC_STATUS_FAILED = "failed"
PUBLIC_STATUS_CLEANUP_FAILED = "cleanup_failed"
PUBLIC_STATUS_IN_PROGRESS = "in_progress"
IN_PROGRESS_ITEM_STATES = frozenset(
    (ITEM_STATE_PENDING, ITEM_STATE_RUNNING, ITEM_STATE_REMOTE_UPLOADED)
)
