TASK_NAME_REGISTRY = {
    "actor_subscription_sync": "订阅演员影片同步",
    "subscribed_movie_auto_download": "已订阅缺失影片自动下载",
    "movie_heat_update": "影片热度更新",
    "movie_interaction_sync": "影片互动数同步",
    "hot_review_sync": "JavDB 热评同步",
    "movie_collection_sync": "合集影片同步",
    "movie_desc_sync": "影片描述回填",
    "movie_desc_translation": "影片简介翻译",
    "movie_title_translation": "影片标题翻译",
    "movie_similarity_recompute": "影片相似度重算",
    "download_task_sync": "下载任务状态同步",
    "download_task_auto_import": "已完成下载自动导入",
    "media_thumbnail_generation": "媒体缩略图生成",
    "image_search_index": "图像搜索索引构建",
    "image_search_optimize": "图像搜索索引优化",
    "download_task_import": "下载任务导入",
    "media_rapid_upload": "批量媒体秒传",
}
